
class PydataCredentialsError(ValueError):
    """
    Raised when invalid credentials are provided, or tokens have expired.
    """
    pass
